### ISSUE TITLE
Change output file name

### ISSUE THREAD

**Issue by jutanke** [BioroboticsLab/biotracker_sampletracker#6]
to better identify trackers the biotracker expects a tracker to be named like: <name>.tracker.so

**Comment by nebw** [comment]
setting  CMAKE_SHARED_LIBRARY_SUFFIX would probably be the right way to do this. See: https://cmake.org/Wiki/CMake_Useful_Variables#Prefixes.2C_Suffixes_.28Postfixes.29.2C_and_Extensions

**Comment by jutanke** [comment]
@Sh4kE please provide more information for why you reopened the issue

**Comment by Sh4kE** [comment]
ahh I don't wanted to reopen it :D In my head I thought we were checking the name exactly to be sampletracker.tracker.exe. I was at reopening while scimming through the code, until I noticed it was only in the comment. What we actually are doing is checking for two dots in the path, thats all. So it was a fault to reopen it, sry...
